version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean build --info
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'application.jar'
    - '.platform/**/*'
  name: application.jar
  discard-paths: no
  base-directory: 'build/libs'
